server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: zone-service
          uri: lb://ZONE-SERVICE
          predicates:
            - Path=/api/zones/**
        - id: sensor-service
          uri: lb://SENSOR-SERVICE
          predicates:
            - Path=/api/sensors/**
        - id: automation-service
          uri: lb://AUTOMATION-SERVICE
          predicates:
            - Path=/api/automation/**
        - id: crop-service
          uri: lb://CROP-SERVICE
          predicates:
            - Path=/api/crops/**

jwt:
  secret: mysupersecretkeymysupersecretkey12345

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info