server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: file:///E:/AD2/AGMS_Microservice/config-repo
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka